name: Handle External Dispatch

on:
  repository_dispatch:
    types: [my-custom-event] # The name of your event

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print raw payload
        run: |
          echo "Full payload received:"
          echo '${{ toJson(github.event.client_payload) }}'

      - name: Access specific JSON properties
        run: |
          echo "Categories:"
          echo '${{ toJson(github.event.client_payload) }}'
